# -*- coding: utf-8 -*-
"""Untitled75.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fyqNt3QUKQl7069zZhHzF7RJ_5NBkqg
"""

!pip install transformers torch streamlit --quiet

import streamlit as st
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import time

# Кэшируем загрузку моделей, чтобы не загружать каждый раз
@st.cache(allow_output_mutation=True)
def load_model(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name)
    return tokenizer, model

# Поддерживаем три модели DialoGPT
model_options = {
    "DialoGPT small": "microsoft/DialoGPT-small",
    "DialoGPT medium": "microsoft/DialoGPT-medium",
    "DialoGPT large": "microsoft/DialoGPT-large"
}

# Простейшие кастомные шаблоны (пример)
custom_templates = {
    "Обычный": lambda text: text,
    "Вежливый": lambda text: "Пожалуйста, " + text,
    "Юморной": lambda text: text + " 😄"
}

# Инициализация состояния
if "history" not in st.session_state:
    st.session_state.history = None
if "chat_log" not in st.session_state:
    st.session_state.chat_log = []
if "selected_model" not in st.session_state:
    st.session_state.selected_model = "DialoGPT small"
if "selected_template" not in st.session_state:
    st.session_state.selected_template = "Обычный"
if "language" not in st.session_state:
    st.session_state.language = "Русский"

st.title("BOtCH Chatbot with Extended Features")

# Выбор модели
selected_model = st.selectbox("Выберите модель DialoGPT", list(model_options.keys()), index=list(model_options.keys()).index(st.session_state.selected_model))
if selected_model != st.session_state.selected_model:
    st.session_state.selected_model = selected_model
    st.session_state.history = None
    st.session_state.chat_log = []
    st.experimental_rerun()

# Загрузка выбранной модели
tokenizer, model = load_model(model_options[st.session_state.selected_model])

# Выбор шаблона ответа
selected_template = st.selectbox("Выберите стиль ответа", list(custom_templates.keys()), index=list(custom_templates.keys()).index(st.session_state.selected_template))
st.session_state.selected_template = selected_template

# Язык (просто для демонстрации, можно улучшить)
language = st.selectbox("Язык интерфейса", ["Русский", "English"], index=0 if st.session_state.language == "Русский" else 1)
st.session_state.language = language

# Функция генерации ответа с таймингом
def generate_response(history, user_input, max_length=1000):
    new_user_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt')
    bot_input_ids = torch.cat([history, new_user_input_ids], dim=-1) if history is not None else new_user_input_ids
    start_time = time.time()
    output_ids = model.generate(bot_input_ids, max_length=max_length, pad_token_id=tokenizer.eos_token_id)
    gen_time = time.time() - start_time
    response_ids = output_ids[:, bot_input_ids.shape[-1]:]
    response_text = tokenizer.decode(response_ids[0], skip_special_tokens=True)
    return output_ids, response_text, gen_time

# Ввод пользователя
user_input = st.text_input("Введите сообщение:", "")

# Кнопки
col1, col2, col3 = st.columns(3)
with col1:
    send_pressed = st.button("Отправить")
with col2:
    clear_pressed = st.button("Очистить историю")
with col3:
    save_pressed = st.button("Сохранить лог в файл")

if clear_pressed:
    st.session_state.history = None
    st.session_state.chat_log = []
    st.experimental_rerun()

if send_pressed and user_input.strip() != "":
    # Применяем шаблон к вопросу (например, для обработки стиля)
    styled_input = custom_templates[st.session_state.selected_template](user_input)
    st.session_state.history, bot_response, gen_time = generate_response(st.session_state.history, styled_input)
    st.session_state.chat_log.append(("Пользователь", user_input))
    st.session_state.chat_log.append(("БОТ", bot_response))
    st.session_state.chat_log.append(("Метрика", f"Время генерации: {gen_time:.2f} сек, Длина ответа: {len(bot_response)} символов"))

if st.session_state.chat_log:
    for speaker, text in st.session_state.chat_log:
        if speaker == "Пользователь":
            st.markdown(f"**{speaker}:** {text}")
        elif speaker == "БОТ":
            st.markdown(f"<div style='color: green'><b>{speaker}:</b> {text}</div>", unsafe_allow_html=True)
        else:  # метрика
            st.markdown(f"<i style='color: gray; font-size: small;'>{text}</i>", unsafe_allow_html=True)

# Сохраняем лог в файл
if save_pressed:
    log_text = ""
    for speaker, text in st.session_state.chat_log:
        log_text += f"{speaker}: {text}\n"
    with open("chat_log.txt", "w", encoding="utf-8") as f:
        f.write(log_text)
    st.success("Лог сохранён в chat_log.txt")
    # Для Colab можно скачать файл (если нужно)
    try:
        from google.colab import files
        files.download("chat_log.txt")
    except ImportError:
        pass